-- Author: saiaapiz
-- TranslateApi v1.0
-- This script using google translate as translator.

-- InputText: String to translate, SystemLangCode: String to translate language code, TargetLangCode: Target Language Code.
function Translate(InputText, SystemLangCode, TargetLangCode)
  _ = InputText __ = SystemLangCode ___ = TargetLangCode
  _ = InputText:gsub("\n", "\r\n") _ = _:gsub("([^%w])", function(c) return string.format("%%%02X", string.byte(c)) end) _ = _:gsub(" ", "%%20")
  Data = gg.makeRequest("https://translate.googleapis.com/translate_a/single?client=gtx&sl="..__.."&tl="..___.."&dt=t&q=".._, {['User-Agent']="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"}).content
  if Data == nil then gg.alert("Failed reaching server, make sure you have internet access.") return nil end
  tData = {} for _ in Data:gmatch("\"(.-)\"") do tData[#tData + 1] = _ end
  return tData[1]
end

langtable = {{},{}} lang_code = {
'af', 'afrikaans',
'sq', 'shqip',
'am', 'አማርኛ',
'ar', 'عربى',
'hy', 'հայերեն',
'az', 'azərbaycanlı',
'eu', 'euskalduna',
'be', 'беларускі',
'bn', 'বাংলা',
'bs', 'bosanski',
'bg', 'български',
'ca', 'català',
'ceb', 'Cebuano',
'ny', 'chichewa',
'zh-cn', '简体中文）',
'zh-tw', '中國傳統的）',
'co', 'Corsu',
'hr', 'Hrvatski',
'cs', 'čeština',
'da', 'dansk',
'nl', 'nederlands',
'en', 'english',
'eo', 'esperanto',
'et', 'eesti keel',
'tl', 'pilipino',
'fi', 'Suomalainen',
'fr', 'français',
'fy', 'frysk',
'gl', 'galego',
'ka', 'ქართველი',
'de', 'deutsch',
'el', 'Ελληνικά',
'gu', 'ગુજરાતી',
'ht', 'kreyol ayisyen',
'ha', 'hausa',
'haw', 'ʻŌlelo Hawaiʻi',
'iw', 'עִברִית',
'hi', 'हिन्दी',
'hmn', 'hmoob',
'hu', 'Magyar',
'is', 'íslensku',
'ig', 'igbo',
'id', 'bahasa Indonesia',
'ga', 'Gaeilge',
'it', 'italiano',
'ja', '日本',
'jw', 'basa jawa',
'kn', 'ಕನ್ನಡ',
'kk', 'қазақ',
'km', 'ខ្មែរ',
'ko', '한국어',
'ku', 'kurdî (kurmancî)',
'ky', 'Кыргызча',
'lo', 'ລາວ',
'la', 'latin',
'lv', 'latviski',
'lt', 'lietuvis',
'lb', 'lëtzebuergesch',
'mk', 'македонски',
'mg', 'malagasy',
'ms', 'melayu',
'ml', 'മലയാളം',
'mt', 'malti',
'mi', 'maori',
'mr', 'मराठी',
'mn', 'монгол',
'my', 'မြန်မာ (ဗမာ)',
'ne', 'नेपाली',
'no', 'norsk',
'ps', 'پښتو',
'fa', 'فارسی',
'pl', 'Polskie',
'pt', 'Português',
'pa', 'ਪੰਜਾਬੀ',
'ro', 'Română',
'ru', 'русский',
'sm', 'samoa',
'gd', 'Gàidhlig na h-Alba',
'sr', 'Српски',
'st', 'sesotho',
'sn', 'shona',
'sd', 'سنڌي',
'si', 'සිංහල',
'sk', 'slovenčina',
'sl', 'Slovenščina',
'so', 'somaliyeed',
'es', 'español',
'su', 'basa sunda',
'sw', 'kiswahili',
'sv', 'svenska',
'tg', 'тоҷикӣ',
'ta', 'தமிழ்',
'te', 'తెలుగు',
'th', 'แบบไทย',
'tr', 'Türk',
'uk', 'українська',
'ur', 'اردو',
'uz', 'ozbek',
'vi', 'Tiếng Việt',
'cy', 'cymraeg',
'xh', 'isiXhosa',
'yi', 'ייִדיש',
'yo', 'yoruba',
'zu', 'zulu',
'fil', 'Filipino',
'he', 'עִברִית',
'ja', '日本'
} --107 языков
